/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PayoutMethodType = IDL.Variant({
  'bank' : IDL.Null,
  'crypto' : IDL.Null,
  'paypal' : IDL.Null,
});
export const PayoutMethod = IDL.Record({
  'methodType' : PayoutMethodType,
  'details' : IDL.Text,
});
export const AdminDashboardStats = IDL.Record({
  'activeTasks' : IDL.Nat,
  'pendingPayouts' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const PayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const Time = IDL.Int;
export const PayoutRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PayoutStatus,
  'method' : PayoutMethod,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'referralCode' : IDL.Text,
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'tasksCompleted' : IDL.Vec(IDL.Nat),
  'referrals' : IDL.Vec(IDL.Text),
  'referredBy' : IDL.Opt(IDL.Text),
});
export const TaskStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'completed' : IDL.Null,
  'available' : IDL.Null,
});
export const ProofSubmission = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'reward' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'submission' : IDL.Opt(ProofSubmission),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPayoutRequest' : IDL.Func([IDL.Nat, PayoutMethod], [IDL.Nat], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
  'getAllPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getReferrals' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setReferralCode' : IDL.Func([IDL.Text], [], []),
  'updatePayoutRequestStatus' : IDL.Func([IDL.Nat, PayoutStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PayoutMethodType = IDL.Variant({
    'bank' : IDL.Null,
    'crypto' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const PayoutMethod = IDL.Record({
    'methodType' : PayoutMethodType,
    'details' : IDL.Text,
  });
  const AdminDashboardStats = IDL.Record({
    'activeTasks' : IDL.Nat,
    'pendingPayouts' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const PayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Time = IDL.Int;
  const PayoutRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PayoutStatus,
    'method' : PayoutMethod,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'referralCode' : IDL.Text,
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'tasksCompleted' : IDL.Vec(IDL.Nat),
    'referrals' : IDL.Vec(IDL.Text),
    'referredBy' : IDL.Opt(IDL.Text),
  });
  const TaskStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'completed' : IDL.Null,
    'available' : IDL.Null,
  });
  const ProofSubmission = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'reward' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'submission' : IDL.Opt(ProofSubmission),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPayoutRequest' : IDL.Func([IDL.Nat, PayoutMethod], [IDL.Nat], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
    'getAllPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getReferrals' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setReferralCode' : IDL.Func([IDL.Text], [], []),
    'updatePayoutRequestStatus' : IDL.Func([IDL.Nat, PayoutStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };