/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboardStats {
  'activeTasks' : bigint,
  'pendingPayouts' : bigint,
  'totalUsers' : bigint,
  'totalEarnings' : bigint,
}
export interface PayoutMethod {
  'methodType' : PayoutMethodType,
  'details' : string,
}
export type PayoutMethodType = { 'bank' : null } |
  { 'crypto' : null } |
  { 'paypal' : null };
export interface PayoutRequest {
  'id' : bigint,
  'status' : PayoutStatus,
  'method' : PayoutMethod,
  'userId' : Principal,
  'createdAt' : Time,
  'amount' : bigint,
}
export type PayoutStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface ProofSubmission { 'url' : [] | [string], 'text' : string }
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'reward' : bigint,
  'title' : string,
  'description' : string,
  'submission' : [] | [ProofSubmission],
}
export type TaskStatus = { 'pendingReview' : null } |
  { 'completed' : null } |
  { 'available' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : string,
  'referralCode' : string,
  'balance' : bigint,
  'name' : string,
  'tasksCompleted' : Array<bigint>,
  'referrals' : Array<string>,
  'referredBy' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayoutRequest' : ActorMethod<[bigint, PayoutMethod], bigint>,
  'createTask' : ActorMethod<[string, string, bigint], undefined>,
  'createUser' : ActorMethod<[string, string], undefined>,
  'getAdminDashboardStats' : ActorMethod<[], AdminDashboardStats>,
  'getAllPayoutRequests' : ActorMethod<[], Array<PayoutRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getReferrals' : ActorMethod<[], Array<UserProfile>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setReferralCode' : ActorMethod<[string], undefined>,
  'updatePayoutRequestStatus' : ActorMethod<[bigint, PayoutStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];