/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PayoutMethod {
    methodType: PayoutMethodType;
    details: string;
}
export type Time = bigint;
export interface Task {
    id: bigint;
    status: TaskStatus;
    reward: bigint;
    title: string;
    description: string;
    submission?: ProofSubmission;
}
export interface ProofSubmission {
    url?: string;
    text: string;
}
export interface PayoutRequest {
    id: bigint;
    status: PayoutStatus;
    method: PayoutMethod;
    userId: Principal;
    createdAt: Time;
    amount: bigint;
}
export interface AdminDashboardStats {
    activeTasks: bigint;
    pendingPayouts: bigint;
    totalUsers: bigint;
    totalEarnings: bigint;
}
export interface UserProfile {
    id: string;
    referralCode: string;
    balance: bigint;
    name: string;
    tasksCompleted: Array<bigint>;
    referrals: Array<string>;
    referredBy?: string;
}
export enum PayoutMethodType {
    bank = "bank",
    crypto = "crypto",
    paypal = "paypal"
}
export enum PayoutStatus {
    pending = "pending",
    approved = "approved",
    declined = "declined"
}
export enum TaskStatus {
    pendingReview = "pendingReview",
    completed = "completed",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPayoutRequest(amount: bigint, method: PayoutMethod): Promise<bigint>;
    createTask(title: string, description: string, reward: bigint): Promise<void>;
    createUser(id: string, name: string): Promise<void>;
    getAdminDashboardStats(): Promise<AdminDashboardStats>;
    getAllPayoutRequests(): Promise<Array<PayoutRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProfile(): Promise<UserProfile>;
    getReferrals(): Promise<Array<UserProfile>>;
    getTasks(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setReferralCode(code: string): Promise<void>;
    updatePayoutRequestStatus(requestId: bigint, newStatus: PayoutStatus): Promise<void>;
}
import type { PayoutMethod as _PayoutMethod, PayoutMethodType as _PayoutMethodType, PayoutRequest as _PayoutRequest, PayoutStatus as _PayoutStatus, ProofSubmission as _ProofSubmission, Task as _Task, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPayoutRequest(arg0: bigint, arg1: PayoutMethod): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayoutRequest(arg0, to_candid_PayoutMethod_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayoutRequest(arg0, to_candid_PayoutMethod_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async getAdminDashboardStats(): Promise<AdminDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAllPayoutRequests(): Promise<Array<PayoutRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayoutRequests();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayoutRequests();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferrals(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferrals();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferrals();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setReferralCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReferralCode(arg0);
            return result;
        }
    }
    async updatePayoutRequestStatus(arg0: bigint, arg1: PayoutStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayoutRequestStatus(arg0, to_candid_PayoutStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayoutRequestStatus(arg0, to_candid_PayoutStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PayoutMethodType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutMethodType): PayoutMethodType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutMethod_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutMethod): PayoutMethod {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutRequest): PayoutRequest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutStatus): PayoutStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ProofSubmission_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProofSubmission): ProofSubmission {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProofSubmission]): ProofSubmission | null {
    return value.length === 0 ? null : from_candid_ProofSubmission_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    methodType: _PayoutMethodType;
    details: string;
}): {
    methodType: PayoutMethodType;
    details: string;
} {
    return {
        methodType: from_candid_PayoutMethodType_n14(_uploadFile, _downloadFile, value.methodType),
        details: value.details
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referralCode: string;
    balance: bigint;
    name: string;
    tasksCompleted: Array<bigint>;
    referrals: Array<string>;
    referredBy: [] | [string];
}): {
    id: string;
    referralCode: string;
    balance: bigint;
    name: string;
    tasksCompleted: Array<bigint>;
    referrals: Array<string>;
    referredBy?: string;
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        balance: value.balance,
        name: value.name,
        tasksCompleted: value.tasksCompleted,
        referrals: value.referrals,
        referredBy: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.referredBy))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    reward: bigint;
    title: string;
    description: string;
    submission: [] | [_ProofSubmission];
}): {
    id: bigint;
    status: TaskStatus;
    reward: bigint;
    title: string;
    description: string;
    submission?: ProofSubmission;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n26(_uploadFile, _downloadFile, value.status),
        reward: value.reward,
        title: value.title,
        description: value.description,
        submission: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.submission))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: [] | [string];
    text: string;
}): {
    url?: string;
    text: string;
} {
    return {
        url: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.url)),
        text: value.text
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PayoutStatus;
    method: _PayoutMethod;
    userId: Principal;
    createdAt: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: PayoutStatus;
    method: PayoutMethod;
    userId: Principal;
    createdAt: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PayoutStatus_n10(_uploadFile, _downloadFile, value.status),
        method: from_candid_PayoutMethod_n12(_uploadFile, _downloadFile, value.method),
        userId: value.userId,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
}): PayoutStatus {
    return "pending" in value ? PayoutStatus.pending : "approved" in value ? PayoutStatus.approved : "declined" in value ? PayoutStatus.declined : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bank: null;
} | {
    crypto: null;
} | {
    paypal: null;
}): PayoutMethodType {
    return "bank" in value ? PayoutMethodType.bank : "crypto" in value ? PayoutMethodType.crypto : "paypal" in value ? PayoutMethodType.paypal : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    completed: null;
} | {
    available: null;
}): TaskStatus {
    return "pendingReview" in value ? TaskStatus.pendingReview : "completed" in value ? TaskStatus.completed : "available" in value ? TaskStatus.available : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PayoutRequest>): Array<PayoutRequest> {
    return value.map((x)=>from_candid_PayoutRequest_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PayoutMethodType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutMethodType): _PayoutMethodType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PayoutMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutMethod): _PayoutMethod {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PayoutStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutStatus): _PayoutStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referralCode: string;
    balance: bigint;
    name: string;
    tasksCompleted: Array<bigint>;
    referrals: Array<string>;
    referredBy?: string;
}): {
    id: string;
    referralCode: string;
    balance: bigint;
    name: string;
    tasksCompleted: Array<bigint>;
    referrals: Array<string>;
    referredBy: [] | [string];
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        balance: value.balance,
        name: value.name,
        tasksCompleted: value.tasksCompleted,
        referrals: value.referrals,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    methodType: PayoutMethodType;
    details: string;
}): {
    methodType: _PayoutMethodType;
    details: string;
} {
    return {
        methodType: to_candid_PayoutMethodType_n5(_uploadFile, _downloadFile, value.methodType),
        details: value.details
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutStatus): {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
} {
    return value == PayoutStatus.pending ? {
        pending: null
    } : value == PayoutStatus.approved ? {
        approved: null
    } : value == PayoutStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutMethodType): {
    bank: null;
} | {
    crypto: null;
} | {
    paypal: null;
} {
    return value == PayoutMethodType.bank ? {
        bank: null
    } : value == PayoutMethodType.crypto ? {
        crypto: null
    } : value == PayoutMethodType.paypal ? {
        paypal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
